CREATE TABLE pessoas(

	ID INT UNSIGNED NULL DEFAULT NULL,
	Nome VARCHAR(50) NULL DEFAULT NULL,
	Sobrenome VARCHAR(50) NULL DEFAULT NULL,
	Endereco VARCHAR(50) NULL DEFAULT NULL,
	Sexo VARCHAR(50) NULL DEFAULT NULL

);
